/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 헬스 체크 — 운영 모드·오디오 설정·캡처/분석 활성 여부 반환.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/recent-actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent Actions
         * @description 최근 자동 적용된 액션 이력 — ADR-0008 §3.6 윈도우 기반 조회.
         *
         *     실 *역 OSC* 송신(롤백)은 콘솔 상태 reader가 들어와야 가능
         *     (docs/hardware-dependent.md #4). 지금은 운영자 가시성·디버깅용 조회만.
         */
        get: operations["recent_actions_control_recent_actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/dry-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Force Dry Run
         * @description ADR-0008 §3 킬 스위치 — 모든 자동 액션 즉시 정지.
         *
         *     config 변경 없이 controller의 effective_mode를 DRY_RUN으로 강제 다운그레이드.
         *     한 번 호출되면 프로세스 재시작 전까지 어떤 액션도 송신되지 않는다.
         *
         *     controller가 없는 경우(audio 비활성)에도 200으로 응답하며 상태 문자열로
         *     알린다 — 멱등성 + 운영자 혼란 방지.
         */
        post: operations["force_dry_run_control_dry_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Recommendations
         * @description Recommendation의 Server-Sent Events 스트림.
         *
         *     각 이벤트는 JSON 본문 + 빈 줄. 15초 동안 새 이벤트가 없으면
         *     `: keep-alive` 코멘트로 연결 유지.
         */
        get: operations["stream_recommendations_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Meters
         * @description 채널별 RMS·peak dBFS 스트림.
         *
         *     `meter_stream.enabled`가 false면 연결은 성립하되 데이터 이벤트가
         *     생기지 않는다(keep-alive만 송신).
         */
        get: operations["stream_meters_meters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionEntry
         * @description `ActionHistory.HistoryEntry`의 API 표면 형태.
         */
        ActionEntry: {
            /** Timestamp */
            timestamp: number;
            /** Channel */
            channel: number;
            /** Kind */
            kind: string;
            /** Osc Messages */
            osc_messages: components["schemas"]["OscMessage"][];
            /** Reason */
            reason: string;
        };
        /**
         * ChannelMeter
         * @description 단일 채널의 미터 스냅샷 — RMS·peak를 dBFS로.
         */
        ChannelMeter: {
            /** Channel */
            channel: number;
            /** Rms Dbfs */
            rms_dbfs: number;
            /** Peak Dbfs */
            peak_dbfs: number;
        };
        /**
         * ControlResponse
         * @description 제어 엔드포인트(`/control/*`) 공통 응답.
         */
        ControlResponse: {
            /** Status */
            status: string;
            /** Effective Mode */
            effective_mode?: string | null;
        };
        /**
         * HealthResponse
         * @description `/health` 응답.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Operating Mode */
            operating_mode: string;
            /** Sample Rate */
            sample_rate: number;
            /** Num Channels */
            num_channels: number;
            /** Audio Enabled */
            audio_enabled: boolean;
            /** Lufs Analysis Enabled */
            lufs_analysis_enabled: boolean;
            /** Feedback Analysis Enabled */
            feedback_analysis_enabled: boolean;
            /** Peak Analysis Enabled */
            peak_analysis_enabled: boolean;
            /** Dynamic Range Analysis Enabled */
            dynamic_range_analysis_enabled: boolean;
            /** Meter Stream Enabled */
            meter_stream_enabled: boolean;
        };
        /**
         * MeterSnapshotEvent
         * @description `/meters` SSE 스트림의 단일 이벤트 페이로드.
         *
         *     한 프레임의 채널별 미터값 묶음. 클라이언트는 capture_seq를 보고 누락
         *     여부를 추적 가능 (단조 증가).
         */
        MeterSnapshotEvent: {
            /** Capture Seq */
            capture_seq: number;
            /** Channels */
            channels: components["schemas"]["ChannelMeter"][];
        };
        /**
         * OscMessage
         * @description 단일 OSC 메시지 — `(address, value)` 한 쌍.
         */
        OscMessage: {
            /** Address */
            address: string;
            /** Value */
            value: number;
        };
        /**
         * RecentActionsResponse
         * @description `GET /control/recent-actions` 응답.
         */
        RecentActionsResponse: {
            /** Entries */
            entries: components["schemas"]["ActionEntry"][];
            /** Window Seconds */
            window_seconds: number;
        };
        /**
         * RecommendationEvent
         * @description `/recommendations` SSE 스트림의 단일 이벤트 페이로드.
         *
         *     각 `data:` 라인 본문에 직렬화되는 JSON. 도메인 `Recommendation`을
         *     JSON 친화 형태로 변환한 결과.
         */
        RecommendationEvent: {
            /** Channel */
            channel: number;
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Kind */
            kind: string;
            /** Params */
            params: {
                [key: string]: number;
            };
            /** Confidence */
            confidence: number;
            /** Reason */
            reason: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    recent_actions_control_recent_actions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentActionsResponse"];
                };
            };
        };
    };
    force_dry_run_control_dry_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlResponse"];
                };
            };
        };
    };
    stream_recommendations_recommendations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events 스트림. 각 'data:' 라인 본문이 RecommendationEvent JSON. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationEvent"];
                    "text/event-stream": unknown;
                };
            };
        };
    };
    stream_meters_meters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events 스트림. 각 'data:' 라인 본문이 MeterSnapshotEvent JSON. 미터는 throttled (`meter_stream.publish_interval_frames`). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeterSnapshotEvent"];
                    "text/event-stream": unknown;
                };
            };
        };
    };
}
