/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 헬스 체크 — 운영 모드·오디오 설정·캡처/분석 활성 여부 반환.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/recent-actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent Actions
         * @description 최근 자동 적용된 액션 이력 — ADR-0008 §3.6 윈도우 기반 조회.
         *
         *     실 *역 OSC* 송신(롤백)은 콘솔 상태 reader가 들어와야 가능
         *     (docs/hardware-dependent.md #4). 지금은 운영자 가시성·디버깅용 조회만.
         */
        get: operations["recent_actions_control_recent_actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Channels
         * @description 현재 채널맵 — `config/channels.yaml`을 그대로 반영.
         *
         *     운영자가 매핑을 외부 편집 후 새로고침해 즉시 확인할 수 있도록 매 요청마다
         *     파일을 다시 읽는다(`reload()` 후 read). 매우 자주 호출되는 경로가 아니라 OK.
         */
        get: operations["get_channels_channels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Channel
         * @description 채널 카테고리·라벨 갱신 — YAML에 즉시 영속, 라이브 루프는 재시작 후 반영.
         *
         *     Body:
         *         category: 'vocal' | 'preacher' | 'choir' | 'instrument' | 'unknown'
         *         label: 자유 문자열 (빈 문자열 허용).
         *
         *     Returns:
         *         갱신 직후의 ChannelMapEntry.
         *
         *     Raises:
         *         HTTP 400: category가 유효하지 않을 때.
         *         HTTP 422: channel_id가 1 이상이 아닐 때 (FastAPI 기본 검증).
         */
        put: operations["update_channel_channels__channel_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rules
         * @description 모든 룰의 현재 토글 상태 — service 도중 운영자 가시용.
         */
        get: operations["get_rules_control_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/rules/{rule_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Rule
         * @description 단일 룰 토글 — 처리 루프는 다음 frame부터 반영(재시작 불필요).
         *
         *     Raises:
         *         HTTP 400: 알 수 없는 룰 이름.
         */
        put: operations["update_rule_control_rules__rule_name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/audit-log/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit Log Recent
         * @description ADR-0008 §3 감사 JSONL의 최근 레코드 — 영구 이력 조회.
         *
         *     `recent-actions`는 메모리 60초 윈도우(applied만), 이 엔드포인트는
         *     디스크 JSONL을 읽어 *모든* 자동 액션 시도(applied·blocked_policy·
         *     blocked_guard)를 최신 순으로 반환.
         *
         *     `audit_log_path`가 None이면 `enabled=false` + 빈 리스트.
         */
        get: operations["audit_log_recent_control_audit_log_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/dry-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Force Dry Run
         * @description ADR-0008 §3 킬 스위치 — 모든 자동 액션 즉시 정지.
         *
         *     config 변경 없이 controller의 effective_mode를 DRY_RUN으로 강제 다운그레이드.
         *     한 번 호출되면 프로세스 재시작 전까지 어떤 액션도 송신되지 않는다.
         *
         *     controller가 없는 경우(audio 비활성)에도 200으로 응답하며 상태 문자열로
         *     알린다 — 멱등성 + 운영자 혼란 방지.
         */
        post: operations["force_dry_run_control_dry_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/operating-mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Operating Mode
         * @description 현재 운영 모드 + 킬 스위치 active 여부.
         *
         *     controller가 없으면(audio 비활성) config의 디폴트 모드를 반환하고
         *     kill_switch_engaged=False.
         */
        get: operations["get_operating_mode_control_operating_mode_get"];
        /**
         * Update Operating Mode
         * @description 평상시 운영 모드 토글 — dry-run/assist/auto.
         *
         *     Raises:
         *         HTTP 400: 알 수 없는 mode.
         *         HTTP 409: 킬 스위치 active 상태에서 호출 — 재시작 강제.
         *         HTTP 503: controller 없음(audio 비활성).
         */
        put: operations["update_operating_mode_control_operating_mode_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reload Thresholds
         * @description graceful 임계·타깃 reload — service 중 환경 변수 갱신 후 호출.
         *
         *     새 `Settings()`를 생성해 `.env`와 현재 환경 변수를 재평가하고,
         *     라이브 갱신 가능한 임계·타깃만 in-place mutate. 처리 루프는 다음
         *     frame부터 새 값으로 평가 — 재시작 불필요.
         *
         *     라이브 변경 불가 영역(audio·LUFS/LRA buffer 크기·detector persistence·
         *     OSC host 등)은 `ignored`로 보고. 그쪽을 바꾸려면 명시적 재시작 필요.
         *
         *     주의: `feedback_pnr_threshold_db`는 평가 시 확인 임계로는 즉시
         *     반영되나, 채널별 `FeedbackDetector`가 갖는 검출 임계는 객체 재생성
         *     없이 갱신되지 않는다(detector는 ignored에 포함).
         */
        post: operations["reload_thresholds_control_reload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Recommendations
         * @description Recommendation의 Server-Sent Events 스트림.
         *
         *     각 이벤트는 JSON 본문 + 빈 줄. 15초 동안 새 이벤트가 없으면
         *     `: keep-alive` 코멘트로 연결 유지.
         */
        get: operations["stream_recommendations_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Meters
         * @description 채널별 RMS·peak dBFS 스트림.
         *
         *     `meter_stream.enabled`가 false면 연결은 성립하되 데이터 이벤트가
         *     생기지 않는다(keep-alive만 송신).
         */
        get: operations["stream_meters_meters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionEntry
         * @description `ActionHistory.HistoryEntry`의 API 표면 형태.
         */
        ActionEntry: {
            /** Timestamp */
            timestamp: number;
            /** Channel */
            channel: number;
            /** Kind */
            kind: string;
            /** Osc Messages */
            osc_messages: components["schemas"]["OscMessage"][];
            /** Reason */
            reason: string;
        };
        /**
         * AuditEntry
         * @description ADR-0008 §3 감사 JSONL의 한 레코드 — applied/blocked 모두 포함.
         */
        AuditEntry: {
            /** Timestamp */
            timestamp: number;
            /** Outcome */
            outcome: string;
            /** Effective Mode */
            effective_mode: string;
            /** Reason */
            reason: string;
            /** Channel */
            channel: number;
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Kind */
            kind: string;
            /** Confidence */
            confidence: number;
            /** Rec Reason */
            rec_reason: string;
            /** Osc Messages */
            osc_messages: components["schemas"]["OscMessage"][];
        };
        /**
         * AuditLogResponse
         * @description `GET /control/audit-log/recent` 응답.
         *
         *     `entries`는 최신 → 과거 순. `enabled=false`면 감사 로그 미설정(서버 운영
         *     환경에서 `audit_log_path`가 None).
         */
        AuditLogResponse: {
            /** Enabled */
            enabled: boolean;
            /** Entries */
            entries: components["schemas"]["AuditEntry"][];
        };
        /**
         * ChannelMapEntry
         * @description 채널맵 한 항목 — `config/channels.yaml`의 한 채널 entry.
         */
        ChannelMapEntry: {
            /** Channel */
            channel: number;
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Stereo Pair With */
            stereo_pair_with?: number | null;
        };
        /**
         * ChannelMapResponse
         * @description `GET /channels` 응답 — 현재 채널맵 전체.
         */
        ChannelMapResponse: {
            /** Entries */
            entries: components["schemas"]["ChannelMapEntry"][];
        };
        /**
         * ChannelMapUpdateRequest
         * @description `PUT /channels/{id}` 요청 body — 카테고리·라벨·stereo 페어 갱신.
         */
        ChannelMapUpdateRequest: {
            /** Category */
            category: string;
            /**
             * Label
             * @default
             */
            label: string;
            /** Stereo Pair With */
            stereo_pair_with?: number | null;
        };
        /**
         * ChannelMeter
         * @description 단일 채널 미터 — 라벨·카테고리·RMS·peak·LRA·옥타브 스펙트럼.
         */
        ChannelMeter: {
            /** Channel */
            channel: number;
            /** Label */
            label: string;
            /** Category */
            category: string;
            /** Rms Dbfs */
            rms_dbfs: number;
            /** Peak Dbfs */
            peak_dbfs: number;
            /** Lra Lu */
            lra_lu?: number | null;
            /**
             * Octave Bands Dbfs
             * @default []
             */
            octave_bands_dbfs: number[];
            /** Stereo Pair With */
            stereo_pair_with?: number | null;
            /** Phase With Pair */
            phase_with_pair?: number | null;
        };
        /**
         * ControlResponse
         * @description 제어 엔드포인트(`/control/*`) 공통 응답.
         */
        ControlResponse: {
            /** Status */
            status: string;
            /** Effective Mode */
            effective_mode?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description `/health` 응답.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Operating Mode */
            operating_mode: string;
            /** Sample Rate */
            sample_rate: number;
            /** Num Channels */
            num_channels: number;
            /** Audio Enabled */
            audio_enabled: boolean;
            /** Lufs Analysis Enabled */
            lufs_analysis_enabled: boolean;
            /** Feedback Analysis Enabled */
            feedback_analysis_enabled: boolean;
            /** Peak Analysis Enabled */
            peak_analysis_enabled: boolean;
            /** Dynamic Range Analysis Enabled */
            dynamic_range_analysis_enabled: boolean;
            /** Lra Analysis Enabled */
            lra_analysis_enabled: boolean;
            /** Phase Analysis Enabled */
            phase_analysis_enabled: boolean;
            /** Meter Stream Enabled */
            meter_stream_enabled: boolean;
            /** Metrics Sink Enabled */
            metrics_sink_enabled: boolean;
        };
        /**
         * MeterSnapshotEvent
         * @description `/meters` SSE 스트림의 단일 이벤트 페이로드.
         *
         *     한 프레임의 채널별 미터값 묶음. 클라이언트는 capture_seq를 보고 누락
         *     여부를 추적 가능 (단조 증가).
         */
        MeterSnapshotEvent: {
            /** Capture Seq */
            capture_seq: number;
            /** Channels */
            channels: components["schemas"]["ChannelMeter"][];
        };
        /**
         * OperatingModeRequest
         * @description `PUT /control/operating-mode` 요청 body — 평상시 모드 토글.
         */
        OperatingModeRequest: {
            /** Mode */
            mode: string;
        };
        /**
         * OperatingModeState
         * @description 현재 운영 모드 상태 — endpoint 응답 + 상태 카드 표시용.
         */
        OperatingModeState: {
            /** Mode */
            mode: string;
            /** Kill Switch Engaged */
            kill_switch_engaged: boolean;
        };
        /**
         * OscMessage
         * @description 단일 OSC 메시지 — `(address, value)` 한 쌍.
         */
        OscMessage: {
            /** Address */
            address: string;
            /** Value */
            value: number;
        };
        /**
         * RecentActionsResponse
         * @description `GET /control/recent-actions` 응답.
         */
        RecentActionsResponse: {
            /** Entries */
            entries: components["schemas"]["ActionEntry"][];
            /** Window Seconds */
            window_seconds: number;
        };
        /**
         * RecommendationEvent
         * @description `/recommendations` SSE 스트림의 단일 이벤트 페이로드.
         *
         *     각 `data:` 라인 본문에 직렬화되는 JSON. 도메인 `Recommendation`을
         *     JSON 친화 형태로 변환한 결과.
         */
        RecommendationEvent: {
            /** Channel */
            channel: number;
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Kind */
            kind: string;
            /** Params */
            params: {
                [key: string]: number;
            };
            /** Confidence */
            confidence: number;
            /** Reason */
            reason: string;
        };
        /**
         * ReloadResponse
         * @description `POST /control/reload` 응답 — graceful 임계 reload 결과 리포트.
         *
         *     `applied_thresholds`: 새 settings로부터 갱신된 임계·타깃 dict.
         *     `ignored`: 라이브 변경 불가 영역(audio·buffer·detector persistence 등) —
         *     값이 바뀌었더라도 재시작 전까지 반영 안 됨. 운영자가 명시적으로 인지하도록
         *     각 항목에 사유 첨부.
         */
        ReloadResponse: {
            /** Applied Thresholds */
            applied_thresholds: {
                [key: string]: unknown;
            };
            /**
             * Ignored
             * @default []
             */
            ignored: {
                [key: string]: string;
            }[];
        };
        /**
         * RuleState
         * @description 단일 룰의 활성 상태.
         */
        RuleState: {
            /** Name */
            name: string;
            /** Enabled */
            enabled: boolean;
        };
        /**
         * RuleToggleRequest
         * @description `PUT /control/rules/{name}` 요청 body.
         */
        RuleToggleRequest: {
            /** Enabled */
            enabled: boolean;
        };
        /**
         * RulesResponse
         * @description `GET /control/rules` 응답 — 모든 룰의 현재 토글 상태.
         */
        RulesResponse: {
            /** Rules */
            rules: components["schemas"]["RuleState"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    recent_actions_control_recent_actions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentActionsResponse"];
                };
            };
        };
    };
    get_channels_channels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelMapResponse"];
                };
            };
        };
    };
    update_channel_channels__channel_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelMapUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelMapEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rules_control_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulesResponse"];
                };
            };
        };
    };
    update_rule_control_rules__rule_name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleToggleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_log_recent_control_audit_log_recent_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    force_dry_run_control_dry_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlResponse"];
                };
            };
        };
    };
    get_operating_mode_control_operating_mode_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatingModeState"];
                };
            };
        };
    };
    update_operating_mode_control_operating_mode_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperatingModeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatingModeState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reload_thresholds_control_reload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReloadResponse"];
                };
            };
        };
    };
    stream_recommendations_recommendations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events 스트림. 각 'data:' 라인 본문이 RecommendationEvent JSON. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationEvent"];
                    "text/event-stream": unknown;
                };
            };
        };
    };
    stream_meters_meters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events 스트림. 각 'data:' 라인 본문이 MeterSnapshotEvent JSON. 미터는 throttled (`meter_stream.publish_interval_frames`). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeterSnapshotEvent"];
                    "text/event-stream": unknown;
                };
            };
        };
    };
}
